apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
      benchmark: nested-pv
      app: nested-pv-breadth
    name: nested-pv
    namespace: cinder-csi-test
spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: nested-pv
    strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
    template:
      metadata:
        labels:
          benchmark: cinder-csi-bench-72868        
          app: cinder-csi-bench-72868-1
          deploymentconfig: cinder-csi-bench-72868-1
      spec:
        containers:
        - name: ubi-playground
          image: registry.redhat.io/ubi8
          args:
          - /bin/sh
          - -c
          - while true; do echo "hello cinder" | tee /data/log.txt && sleep 10 ;done
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data
            name: persistent-storage
        volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: data-72868-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
